# generated by mk-ks-offline-repos.sh
repo --name=oj_x86_64 --baseurl=file:///opt/proj/oj4/ojbs/localrepos/oj_x86_64
repo --name=3d_party --baseurl=file:///opt/proj/oj4/ojbs/localrepos/3d_party
repo --name=cached --baseurl=file:///opt/proj/oj4/ojbs/localrepos/cached

