# generated by mk-oj-repo.sh
repo --name=oj16 --mirrorlist=http://mirrors.ojuba.org/repo=os+arch=$basearch+release=16
repo --name=oj16-updates --mirrorlist=http://mirrors.ojuba.org/repo=updates+arch=$basearch+release=16

repo --name=oj16-testing --mirrorlist=http://mirrors.ojuba.org/repo=testing+arch=$basearch+release=16
