# generated by mk-oj-repo.sh
repo --name=oj5 --mirrorlist=http://www.ojuba.org/.mirrors-oj5-$basearch
repo --name=oj5-updates --mirrorlist=http://www.ojuba.org/.mirrors-oj5-$basearch-updates

repo --name=oj5-testing --mirrorlist=http://www.ojuba.org/.mirrors-oj5-$basearch-testing
