# generated by mk-oj-repo.sh
#repo --name=oj17 --mirrorlist=http://mirrors.ojuba.org/repo=os+arch=$basearch+release=17
#repo --name=oj17-updates --mirrorlist=http://mirrors.ojuba.org/repo=updates+arch=$basearch+release=17

#repo --name=oj17-testing --mirrorlist=http://mirrors.ojuba.org/repo=testing+arch=$basearch+release=17
