#! /bin/bash
d=$(dirname "$0")
d="$(readlink -f $d)"
pushd "$d/../"
  . buildsys.conf
  
  echo "# generated by $( basename $0 )
repo --name=oj$oj --mirrorlist=http://www.ojuba.org/.mirrors-oj$oj-$basearch
repo --name=oj$oj-updates --mirrorlist=http://www.ojuba.org/.mirrors-oj$oj-$basearch-updates
" > ks/oj/repos-oj.ks
  [ ! -z $is_testing ] && echo "repo --name=oj$oj-testing --mirrorlist=http://www.ojuba.org/.mirrors-oj$oj-$basearch-testing" >> ks/oj/repos-oj.ks

popd


