#! /bin/bash
d=$(dirname "$0")
d="$(readlink -f $d)"
pushd "$d/../"
  . buildsys.conf
  
  echo "# generated by $( basename $0 )
repo --name=oj$fedora_release --mirrorlist=http://mirrors.ojuba.org/repo=os+arch=\$basearch+release=$fedora_release
repo --name=oj$fedora_release-updates --mirrorlist=http://mirrors.ojuba.org/repo=updates+arch=\$basearch+release=$fedora_release
" > ks/oj/repos-oj.ks
  [ ! -z $is_testing ] && echo "repo --name=oj$fedora_release-testing --mirrorlist=http://mirrors.ojuba.org/repo=testing+arch=\$basearch+release=$fedora_release" >> ks/oj/repos-oj.ks

popd


